version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      SESSION_STRING: $SESSION_STRING
      STREAM_URL: $STREAM_URL
      LOG_GROUP: $LOG_GROUP
      ADMINS: $ADMINS
      CHAT: $CHAT
      MAXIMUM_DURATION: $MAXIMUM_DURATION
      REPLY_MESSAGE: $REPLY_MESSAGE
      ADMIN_ONLY: $ADMIN_ONLY
